Repository codeit-team2/codeit-team2-fe, pull requests merged in 2024-08, with the labels that each got.

#212 디자인 2차 검수 사항 반영
  public/icons/ic-close-button.svg
  src/components/Detail/FloatingBar/index.tsx
  src/components/Detail/InfoBadge/index.tsx
  src/components/Detail/TitleCard/index.tsx
  src/components/Review/StarRatingAverage/index.tsx
  src/components/Review/UserReview/index.tsx
  src/components/common/Banner/index.tsx
  src/components/common/Bookmark/index.tsx
  src/components/common/Modal/LoginRequired/index.tsx
  src/pages/detail/[id]/index.tsx
  src/pages/review/index.tsx
Labels: 🛠️ Refactor

#213 모임 만들기 스크롤 디자인 적용 및 모바일 설정
  src/components/ChipTap/index.tsx
  src/components/MakeClub/DropdownInput/index.tsx
  src/components/MakeClub/FileInput/index.tsx
  src/components/MakeClub/Modal/index.tsx
  src/components/common/Modal/Signup/index.tsx
  src/components/ui/button.tsx
  src/hooks/useIsScrollbarVisible.ts
  src/hooks/useIsTablet.ts
  src/pages/make-club/index.tsx
Labels: ✨ Feature, 🎨 UI

#220 로그인 요청 모달 나와야 하는 곳에 적용하기
  src/components/Card/index.tsx
  src/components/Detail/FloatingBar/index.tsx
  src/components/MakeClub/Modal/index.tsx
  src/components/common/Dropdown/index.tsx
  src/components/common/GNB/index.tsx
  src/components/common/Modal/Login/index.tsx
  src/components/common/Modal/LoginRequired/index.tsx
  src/components/ui/button.tsx
  src/context/AuthProvider.tsx
  src/hooks/useCheckLogin.ts
  src/hooks/useCheckLogin.tsx
  src/pages/_app.tsx
  src/pages/index.tsx
  src/pages/make-club/index.tsx
  src/pages/my/index.tsx
Labels: ✨ Feature

#223 로고 호버 시 이미지 변경 및 모달 그라디언트 적용
  public/icons/ic-logo-blue.svg
  src/components/MakeClub/Modal/index.tsx
  src/components/common/Banner/index.tsx
  src/components/common/GNB/index.tsx
  src/components/common/Input/index.tsx
  src/components/common/Modal/Login/index.tsx
  src/components/common/Modal/Signup/index.tsx
  src/components/ui/button.tsx
  src/pages/index.tsx
  src/pages/login/index.tsx
  src/pages/signup/index.tsx
Labels: ✨ Feature

#224 별점 순 정렬 추가 및 오류 수정
  src/apis/reviews.ts
  src/components/Card/index.tsx
  src/components/Detail/TitleCard/index.tsx
  src/hooks/useReviews.ts
  src/lib/utils.ts
  src/pages/review/index.tsx
Labels: 🛠️ Refactor

#230 모임 상세, 활동 후기 페이지 디자인 2차 검수 사항 수정
  src/components/Detail/FloatingBar/index.tsx
  src/components/NotReview/index.tsx
  src/components/Review/StarRatingAverage/index.tsx
  src/components/Review/UserReview/index.tsx
  src/pages/detail/[id]/index.tsx
  src/pages/my/review-available.tsx
  src/pages/my/review-complete.tsx
  src/pages/review/index.tsx
Labels: 🛠️ Refactor, 🎨 UI

#234 Input, Banner 컴포넌트 테스트 코드 작성
  __tests__/banner.test.tsx
  __tests__/input.test.tsx
  jest.config.ts
  package-lock.json
  package.json
  src/apis/auths.ts
Labels: ✅ Test

#236 참여하기 버튼 클릭 시 데이터 변경 수정, 최종 배포 빌드 오류 확인
  src/components/Card/index.tsx
Labels: 🛠️ Refactor, ⚙ Setting

#239 수정 사항 반영
  src/components/Detail/FloatingBar/index.tsx
  src/components/My/MyCard/index.tsx
  src/components/common/Toast/index.tsx
Labels: ✨ Feature, 🛠️ Refactor
