Repository codeit-team2/codeit-team2-fe, pull requests merged in 2024-07, with the labels that each got.

#16 Reviewers & Assignees 자동 지정 Action
  .github/workflows/main.yml
Labels: ✅ Test

#14 모달 컴포넌트
  package-lock.json
  package.json
  src/components/common/Modal/Activity/index.tsx
  src/components/common/Modal/PopUp/index.tsx
  src/components/common/Modal/Profile/index.tsx
  src/components/common/index.tsx
  src/components/ui/dialog.tsx
  src/pages/index.tsx
Labels: ✨ Feature

#17 Button UI 구현
  .firebase/hosting.cHVibGlj.cache
  .firebaserc
  firebase.json
  public/404.html
  public/index.html
  src/components/ui/button.tsx
  src/pages/index.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: 🎨 UI

#23 feat: Banner 컴포넌트 구현
  src/components/common/Banner/index.tsx
Labels: 🎨 UI

#28 Typography, Shape 속성 설정
  src/components/common/GNB/index.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: ⚙ Setting

#29 Feat/tap/21
  public/icons/blackboardIcon.svg
  public/icons/bookIcon.svg
  public/icons/diamondIcon.svg
  public/icons/eyeIcon.svg
  public/icons/fireIcon.svg
  src/components/common/dropdown/index.tsx
  src/components/common/tap/index.tsx
Labels: ✨ Feature

#30 카드 컴포넌트 구현
  public/icons/heart-gray.svg
  public/icons/heart-pink.svg
  public/images/등산이미지.png
  public/images/러닝이미지.jpg
  public/images/풋살이미지.jpeg
  src/components/Card/index.tsx
  src/components/Card/testData.json
  src/pages/index.tsx
Labels: ✨ Feature

#39 button 수정
  src/components/ui/button.tsx
Labels: 🛠️ Refactor

#40 feat: Calendar Component 구현
  package-lock.json
  package.json
  src/components/common/Calendar/index.tsx
  src/components/ui/calendar.tsx
  src/pages/index.tsx
Labels: ✨ Feature

#42 Feat/home/32
  package-lock.json
  public/icons/basePersonIcon.svg
  public/icons/dropdownArray.svg
  public/icons/dropdownIcon.svg
  public/icons/overPersonIcon.svg
  src/components/Card/index.tsx
  src/components/Card/testData.js
  src/components/Card/testData.json
  src/components/ChipTap/MockDatas.js
  src/components/ChipTap/index.tsx
  src/components/common/Banner/index.tsx
  src/components/common/GNB/index.tsx
  src/components/common/MainLayout/index.tsx
  src/components/common/dropdown/index.tsx
  src/components/common/tap/index.tsx
  src/components/ui/button.tsx
  src/components/ui/calendar.tsx
  src/pages/index.tsx
  tailwind.config.ts
Labels: ✨ Feature

#44 Refactor/home/43
  public/icons/plus.svg
  src/components/Card/Description.tsx
  src/components/Card/Liked.tsx
  src/components/Card/Person.tsx
  src/components/Card/ProgressPercentage.tsx
  src/components/Card/index.tsx
  src/components/CreateHobby/index.tsx
  src/pages/index.tsx
Labels: 🛠️ Refactor

#47 UI/footer/45
  public/icons/facebook.svg
  public/icons/instagram.svg
  public/icons/twitter.svg
  src/components/common/Footer/index.tsx
  src/components/common/tap/index.tsx
  src/pages/index.tsx
Labels: ✨ Feature, 🎨 UI

#46 Detail 페이지 구현
  public/icons/check-off.svg
  public/icons/check-on.svg
  public/icons/close.svg
  public/icons/heart-type-off.svg
  public/icons/heart-type-on.svg
  public/icons/login-required.svg
  public/icons/messageicon.svg
  public/icons/person.svg
  public/icons/share-button.svg
  public/icons/star-empty.svg
  public/icons/star-filled.svg
  public/icons/개설확정뱃지.svg
  public/images/none-review.png
  public/images/profileimage.jpeg
  src/components/Detail/FloatingBar/index.tsx
  src/components/Detail/ReviewCard/index.tsx
  src/components/Detail/TitleCard/index.tsx
  src/components/Detail/mockData.json
  src/components/Detail/reviewData.json
  src/components/common/Bookmark/index.tsx
  src/components/common/Modal/LoginRequired/index.tsx
  src/pages/detail/index.tsx
  tailwind.config.ts
Labels: ✨ Feature

#41 Feat/make club/36
  src/components/MakeClub/Modal/index.tsx
  src/components/ui/button.tsx
  src/components/ui/calendar.tsx
  src/components/ui/dialog.tsx
Labels: ✨ Feature

#50 NotCard 구현
  src/components/NotCard/index.tsx
  src/pages/index.tsx
Labels: 🎨 UI

#51 input 기능, login, signup 구현
  package-lock.json
  public/icons/ic-checkbox-off.svg
  public/icons/ic-checkbox-on.svg
  public/icons/ic-error.svg
  public/icons/ic-eye-off.svg
  public/icons/ic-eye-on.svg
  public/icons/ic-success.svg
  public/icons/ic-xmark.svg
  src/components/common/GNB/index.tsx
  src/components/common/Input/index.tsx
  src/components/common/Modal/Login/index.tsx
  src/components/common/Modal/Signup/index.tsx
  src/components/ui/dialog.tsx
  src/constants/formMessages.ts
  src/styles/globals.css
Labels: ✨ Feature

#62 svg 파일 정리
  public/icons/basePersonIcon.svg
  public/icons/check-off.svg
  public/icons/check-on.svg
  public/icons/heart-gray.svg
  public/icons/heart-pink.svg
  public/icons/ic-blackboard.svg
  public/icons/ic-book.svg
  public/icons/ic-chevron-down.svg
  public/icons/ic-chevron-updown.svg
  public/icons/ic-close.svg
  public/icons/ic-diamond.svg
  public/icons/ic-edit-gray.svg
  public/icons/ic-eye.svg
  public/icons/ic-facebook.svg
  public/icons/ic-fire.svg
  public/icons/ic-heart-off.svg
  public/icons/ic-heart-on.svg
  public/icons/ic-instagram.svg
  public/icons/ic-logo.svg
  public/icons/ic-message.svg
  public/icons/ic-person-blue.svg
  public/icons/ic-person-gray.svg
  public/icons/ic-plus.svg
  public/icons/ic-profile.svg
  public/icons/ic-share.svg
  public/icons/ic-star-off.svg
  public/icons/ic-star-on.svg
  public/icons/ic-twitter.svg
  public/icons/login-required.svg
  public/icons/overPersonIcon.svg
  public/icons/plus.svg
  public/images/login.png
  src/components/Card/Liked.tsx
  src/components/Card/Person.tsx
  src/components/CreateHobby/index.tsx
  src/components/Detail/FloatingBar/index.tsx
  src/components/Detail/ReviewCard/index.tsx
  src/components/MakeClub/Modal/index.tsx
  src/components/common/Bookmark/index.tsx
  src/components/common/Button/Edit/index.tsx
  src/components/common/Footer/index.tsx
  src/components/common/GNB/index.tsx
  src/components/common/Modal/LoginRequired/index.tsx
  src/components/common/dropdown/index.tsx
  src/components/common/tap/index.tsx
  src/pages/detail/index.tsx
  src/pages/index.tsx
Labels: ⚙ Setting

#66 refactor: 이미지 경로 수정, CreateHobby버튼수정
  src/components/Card/Liked.tsx
  src/components/CreateHobby/index.tsx
  src/components/MakeClub/Modal/index.tsx
  src/components/NotCard/index.tsx
  src/components/common/Footer/index.tsx
  src/components/common/GNB/index.tsx
  src/components/common/dropdown/index.tsx
  src/components/common/tap/index.tsx
  src/pages/index.tsx
Labels: 🛠️ Refactor

#68 Feat/card design/61
  src/components/Card/Description.tsx
  src/components/Card/index.tsx
  src/components/Card/testData.js
  src/components/My/MyCard/index.tsx
  src/hooks/useFormatDate.ts
  src/hooks/useIsDateBeforeToday.ts
  src/pages/index.tsx
  src/pages/my/meeting.tsx
Labels: ✨ Feature

#75 Feat/my review/69
  public/icons/ic-delete.svg
  public/icons/ic-share.svg
  src/components/Card/index.tsx
  src/components/Card/testData.js
  src/components/My/MyCard/index.tsx
  src/components/My/Profile/index.tsx
  src/components/common/Banner/index.tsx
  src/pages/index.tsx
  src/pages/my/club.tsx
  src/pages/my/index.tsx
  src/pages/my/meeting.tsx
  src/pages/my/review.tsx
  src/types/index.ts
Labels: ✨ Feature

#79 후기 작성 모달 구현
  package-lock.json
  package.json
  src/components/My/MyCard/index.tsx
  src/components/My/Profile/index.tsx
  src/components/common/Modal/Review/index.tsx
  src/components/common/Textarea/index.tsx
  src/components/common/dropdown/index.tsx
  src/components/common/index.tsx
  src/constants/formMessages.ts
  src/pages/index.tsx
Labels: ✨ Feature

#81 Review 페이지 구현
  public/images/badmintonimage.jpeg
  public/images/climbingimage.jpeg
  public/images/futsalimage.jpeg
  public/images/gymimage.jpeg
  public/images/hikingimage.jpeg
  public/images/miscimage.jpeg
  public/images/profileImage1.jpeg
  public/images/runningimage.jpeg
  public/images/tennisimage.jpeg
  public/images/yogaimage.jpeg
  src/components/Detail/ReviewCard/index.tsx
  src/components/NotReview/index.tsx
  src/components/Review/StarRatingAverage/index.tsx
  src/components/Review/UserReview/index.tsx
  src/components/Review/reviewTestData.json
  src/components/common/Banner/index.tsx
  src/components/common/Modal/ReviewModal/index.tsx
  src/components/common/dropdown/index.tsx
  src/pages/detail/index.tsx
  src/pages/index.tsx
  src/pages/review/index.tsx
  tailwind.config.ts
Labels: ✨ Feature

#88 Feat/localstorage/80
  src/components/Card/Description.tsx
  src/components/Card/Person.tsx
  src/components/Card/ProgressPercentage.tsx
  src/components/Card/index.tsx
  src/components/Card/testData.js
  src/components/CreateHobby/index.tsx
  src/components/common/dropdown/index.tsx
  src/hooks/useFavorite.ts
  src/pages/bookmark/index.tsx
  src/pages/index.tsx
Labels: 🐛 Bug, ✨ Feature

#91 eslint, prettier 이슈, import 이슈 수정
  .eslintrc.json
  .github/ISSUE_TEMPLATE/이슈-생성-템플릿.md
  .github/pull_request_template.md
  .prettierrc
  package-lock.json
  package.json
  public/404.html
  public/index.html
  src/components/ApiTest/index.tsx
  src/components/Card/Person.tsx
  src/components/Card/index.tsx
  src/components/ChipTap/index.tsx
  src/components/Detail/FloatingBar/index.tsx
  src/components/Detail/InfoBadge/index.tsx
  src/components/Detail/ProfileImageGroup/index.tsx
  src/components/Detail/ReviewCard/index.tsx
  src/components/Detail/TitleCard/index.tsx
  src/components/MakeClub/Modal/index.tsx
  src/components/My/MyCard/index.tsx
  src/components/My/MyTab/index.tsx
  src/components/My/Profile/index.tsx
  src/components/NotCard/index.tsx
  src/components/NotReview/index.tsx
  src/components/Review/StarRatingAverage/index.tsx
  src/components/Review/UserReview/index.tsx
  src/components/common/Bookmark/index.tsx
  src/components/common/Calendar/index.tsx
  src/components/common/Dropdown/index.tsx
  src/components/common/GNB/index.tsx
  src/components/common/Input/index.tsx
  src/components/common/Modal/Activity/index.tsx
  src/components/common/Modal/Login/index.tsx
  src/components/common/Modal/LoginRequired/index.tsx
  src/components/common/Modal/PopUp/index.tsx
  src/components/common/Modal/ProfileEdit/index.tsx
  src/components/common/Modal/Review/index.tsx
  src/components/common/Modal/Signup/index.tsx
  src/components/common/Tap/index.tsx
  src/components/common/Textarea/index.tsx
  src/components/ui/button.tsx
  src/components/ui/calendar.tsx
  src/components/ui/dialog.tsx
  src/hooks/useIsMobile.tsx
  src/pages/404.tsx
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/bookmark/index.tsx
  src/pages/detail/index.tsx
  src/pages/index.tsx
  src/pages/my/club.tsx
  src/pages/my/index.tsx
  src/pages/my/meeting.tsx
  src/pages/my/review.tsx
  src/pages/review/index.tsx
Labels: 🛠️ Refactor, ⚙ Setting

#97 로그인, 회원가입 api 모듈화
  .gitignore
  src/apis/auths.ts
  src/hooks/useAuths.tsx
  src/lib/axios.ts
  src/pages/_app.tsx
  src/types/auths.ts
Labels: ✨ Feature

#99 1차 배포 v3
  .prettierrc
  src/components/Card/index.tsx
  src/components/Detail/FloatingBar/index.tsx
  src/components/Detail/InfoBadge/index.tsx
  src/components/Detail/ProfileImageGroup/index.tsx
  src/components/Detail/ReviewCard/index.tsx
  src/components/Detail/TitleCard/index.tsx
  src/components/MakeClub/Modal/index.tsx
  src/components/My/MyCard/index.tsx
  src/components/Review/StarRatingAverage/index.tsx
  src/components/Review/UserReview/index.tsx
  src/components/common/Dropdown/index.tsx
  src/components/common/GNB/index.tsx
  src/components/common/Modal/Activity/index.tsx
  src/components/common/Modal/Login/index.tsx
  src/components/common/Modal/LoginRequired/index.tsx
  src/components/common/Modal/Signup/index.tsx
  src/pages/bookmark/index.tsx
  src/pages/review/index.tsx
  src/types/testDataType.ts
  tailwind.config.ts
Labels: 🛠️ Refactor

#106 loading애니메이션 구현
  package-lock.json
  package.json
  public/images/loadingLottie.json
  src/components/Card/index.tsx
  src/components/Loading/index.tsx
  src/hooks/useFavorite.ts
  src/pages/bookmark/index.tsx
  src/pages/index.tsx
  tailwind.config.ts
Labels: ✨ Feature

#110 build에러 해결, pages/my/review useIsDateBeforeToday 에러 미 해결
  src/components/ChipTap/index.tsx
  src/components/My/Profile/index.tsx
  src/components/common/Modal/LoginRequired/index.tsx
  src/components/common/Modal/PopUp/index.tsx
  src/components/common/Modal/ProfileEdit/index.tsx
  src/components/common/Modal/Review/index.tsx
  src/components/common/Textarea/index.tsx
  src/components/ui/calendar.tsx
  src/hooks/useFavorite.ts
  src/pages/bookmark/index.tsx
Labels: 🐛 Bug

#103 Refactor/design/96
  .gitignore
  src/components/MakeClub/FileInput/index.tsx
  src/components/MakeClub/Modal/index.tsx
  src/components/My/MyTab/index.tsx
  src/components/common/Dropdown/index.tsx
  src/constants/formMessages.ts
  src/pages/my/index.tsx
  src/types/index.ts
Labels: 🛠️ Refactor

#112 모달 스크롤바 디자인 설정
  src/apis/auths.ts
  src/components/My/MyCard/index.tsx
  src/components/common/GNB/index.tsx
  src/components/common/Modal/Login/index.tsx
  src/components/common/Modal/ProfileEdit/index.tsx
  src/components/common/Modal/Review/index.tsx
  src/components/common/Modal/Signup/index.tsx
  src/components/common/Tap/index.tsx
  src/components/ui/dialog.tsx
  src/styles/globals.css
Labels: ✨ Feature

#116 찜 버튼 애니메이션 구현
  public/icons/ic-heart-bg-off.svg
  public/icons/ic-heart-bg-on.svg
  public/icons/ic-heart-off.svg
  public/icons/ic-heart-on.svg
  src/components/Card/index.tsx
  src/components/Detail/TitleCard/index.tsx
  src/components/common/Bookmark/index.tsx
  tailwind.config.ts
Labels: ✨ Feature

#118 dropdown calendar생성
  src/components/common/Calendar/index.tsx
  src/components/common/Dropdown/index.tsx
  src/hooks/useFormatedDate.ts
Labels: ✨ Feature

#120 feat: calendar 디자인 수정
  src/components/common/Calendar/index.tsx
  src/components/common/Dropdown/index.tsx
  src/components/ui/calendar.tsx
  src/constants/formMessages.ts
  src/types/index.ts
Labels: ✨ Feature

#135 Feat/make club error/134
  src/apis/gatherings.ts
  src/components/MakeClub/DropdownInput/index.tsx
  src/components/MakeClub/FileInput/index.tsx
  src/components/MakeClub/Modal/index.tsx
  src/components/common/Dropdown/index.tsx
  src/constants/formMessages.ts
  src/constants/timeItems.ts
  src/hooks/useGatherings.tsx
  src/hooks/useIsDateBeforeToday.ts
  src/lib/user.ts
Labels: ✨ Feature

#139 회원가입, 로그인 기능 구현
  package-lock.json
  package.json
  src/apis/accounts.ts
  src/apis/auths.ts
  src/components/common/GNB/index.tsx
  src/components/common/Input/index.tsx
  src/components/common/Modal/Login/index.tsx
  src/components/common/Modal/Signup/index.tsx
  src/constants/formMessages.ts
  src/hooks/useAccounts.ts
  src/hooks/useAuths.ts
  src/hooks/useCheckLogin.ts
  src/lib/axios.ts
  src/pages/my/index.tsx
  src/types/accounts.ts
  src/types/auths.ts
Labels: ✨ Feature

#144 Detail 페이지 모임참여, 모임참여취소, 모임취소(삭제) api 연동
  package.json
  src/apis/gatherings.ts
  src/components/Detail/FloatingBar/index.tsx
  src/components/common/Modal/Check/index.tsx
  src/hooks/useGatherings.ts
  src/hooks/useGatherings.tsx
  src/pages/detail/[id]/index.tsx
  src/types/gatherings.ts
Labels: ✨ Feature

#145 main 페이지 api연동 작업
  package-lock.json
  package.json
  src/apis/gatherings.ts
  src/components/Card/Description.tsx
  src/components/Card/Person.tsx
  src/components/Card/ProgressPercentage.tsx
  src/components/Card/index.tsx
  src/components/ChipTap/MockDatas.js
  src/components/ChipTap/index.tsx
  src/components/Loading/index.tsx
  src/components/common/Bookmark/index.tsx
  src/components/common/Dropdown/index.tsx
  src/components/common/Footer/index.tsx
  src/components/common/MainLayout/index.tsx
  src/components/common/Tap/index.tsx
  src/constants/dropdownItems.ts
  src/hooks/useFavorite.ts
  src/hooks/useGatherings.ts
  src/pages/_app.tsx
  src/pages/bookmark/index.tsx
  src/pages/index.tsx
  src/types/gathering.ts
  src/types/gatherings.ts
  tailwind.config.ts
Labels: ✨ Feature

#152 bookmark페이지 Tap,ChipTap,location까지 완료/ Calendar,sort 미완성
  src/hooks/useFavorite.ts
  src/pages/bookmark/index.tsx
Labels: ✨ Feature

#171 모임 상세, 활동 후기 페이지 수정
  src/components/Detail/FloatingBar/index.tsx
  src/components/Detail/InfoBadge/index.tsx
  src/components/Detail/ReviewCard/index.tsx
  src/components/Detail/TitleCard/index.tsx
  src/components/Review/StarRatingAverage/index.tsx
  src/components/common/Bookmark/index.tsx
  src/components/common/Footer/index.tsx
  src/pages/detail/[id]/index.tsx
  src/pages/review/index.tsx
  tailwind.config.ts
Labels: 🛠️ Refactor

#175 유저 정보 수정 기능, 탈퇴 기능 구현
  src/apis/accounts.ts
  src/components/My/Profile/index.tsx
  src/components/common/GNB/index.tsx
  src/components/common/Input/index.tsx
  src/components/common/Modal/ProfileEdit/index.tsx
  src/components/common/Modal/Review/index.tsx
  src/components/ui/button.tsx
  src/components/ui/dialog.tsx
  src/hooks/useAccounts.ts
  src/hooks/useAuths.ts
  src/hooks/useReviews.ts
  src/types/accounts.ts
  src/types/auths.ts
  src/types/reviews.ts
Labels: ✨ Feature

#179 모임 상세 페이지 리뷰, 모임 참여 인원 데이터 연동
  src/apis/gatherings.ts
  src/components/Detail/InfoBadge/index.tsx
  src/components/Detail/ProfileImageGroup/index.tsx
  src/components/Detail/ReviewCard/index.tsx
  src/components/Detail/TitleCard/index.tsx
  src/hooks/useGatherings.ts
  src/pages/detail/[id]/index.tsx
  src/pages/review/index.tsx
  src/types/gatherings.ts
Labels: ✨ Feature

#184 mutate 형태 변경
  package-lock.json
  package.json
  src/components/common/GNB/index.tsx
  src/components/common/Modal/Login/index.tsx
  src/components/common/Modal/ProfileEdit/index.tsx
  src/components/common/Modal/Signup/index.tsx
  src/hooks/useAccounts.ts
  src/hooks/useAuths.ts
  src/pages/bookmark/index.tsx
  src/pages/login/index.tsx
  src/pages/signup/index.tsx
  src/types/auths.ts
  tsconfig.json
Labels: 🐛 Bug

#187 데이터 리팩토링
  public/favicon.ico
  src/apis/gatherings.ts
  src/apis/reviews.ts
  src/components/Card/index.tsx
  src/components/Detail/FloatingBar/index.tsx
  src/components/Detail/reviewData.json
  src/components/Review/reviewTestData.json
  src/hooks/useGatherings.ts
  src/hooks/useReviews.ts
  src/pages/detail/[id]/index.tsx
  src/pages/review/index.tsx
Labels: 🛠️ Refactor

#189 5차 빋드 에러 수정
  src/components/Card/index.tsx
  src/components/NotReview/index.tsx
  src/components/common/Dropdown/index.tsx
  src/components/common/MainLayout/index.tsx
  src/components/common/Modal/Review/index.tsx
  src/components/ui/dialog.tsx
  src/lib/utils.ts
  src/pages/detail/[id]/index.tsx
Labels: ⚙ Setting

#191 Card hover,active적용 Dropdown scroll-bar제거
  src/components/Card/index.tsx
  src/components/common/Dropdown/index.tsx
  src/pages/index.tsx
Labels: 🛠️ Refactor

#192 계정 탈퇴 버튼 및 모달 변경
  public/icons/ic-edit.svg
  public/icons/ic-setting-gray.svg
  public/icons/ic-setting.svg
  public/images/sad-face.png
  src/components/My/Profile/index.tsx
  src/components/common/Banner/index.tsx
  src/components/common/Button/Edit/index.tsx
  src/components/common/GNB/index.tsx
  src/components/common/Modal/Dynamic/index.tsx
  src/components/common/Modal/ProfileEdit/index.tsx
  src/components/common/Modal/Signup/index.tsx
  src/components/common/Modal/Withdraw/index.tsx
  src/components/ui/button.tsx
  tailwind.config.ts
Labels: ✨ Feature

#197 메인페이지 지역 선택 시 전체도 나오게 하기
  src/components/common/Dropdown/index.tsx
Labels: ✨ Feature

#200 main페이지 찜하기 버튼 페이지 리로드 이후 클릭시 로컬스토리지에 중복 추가되는 이슈 해결
  src/hooks/useFavorite.ts
Labels: 🐛 Bug

#206 카드 기본 상태 테두리 설정 및 카드 이미지 사이즈 통일
  public/icons/ic-person-delete-gray.svg
  public/icons/ic-person-delete.svg
  src/components/Card/index.tsx
  src/components/My/GatheringReviewCard/index.tsx
  src/components/My/MyCard/index.tsx
  src/components/My/Profile/index.tsx
  src/components/My/ReviewCard/index.tsx
  src/components/Review/UserReview/index.tsx
  src/components/common/Banner/index.tsx
  src/components/common/Bookmark/index.tsx
Labels: 🎨 UI
